// <autogenerated />

namespace EBook.Downloader.Calibre.Opf
{
    /// <remarks/>
    [System.Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = Namespaces.Opf)]
    public partial class GuideReference
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("href")]
        public string Href { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("type")]
        public string Type { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("title")]
        public string Title { get; set; }
    }
}
