// <autogenerated />

namespace EBook.Downloader.Calibre.Opf
{
    /// <remarks/>
    [System.Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = Namespaces.Opf)]
    public partial class Guide
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElement("reference")]
        public GuideReference Reference { get; set; }
    }
}
