// <autogenerated />

namespace EBook.Downloader.Calibre.Opf
{
    /// <remarks/>
    [System.Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = Namespaces.Opf)]
    public partial class Item
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("href")]
        public string Href { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("id")]
        public string Id { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("media-type")]
        public string MediaType { get; set; }
    }
}
