// <autogenerated />

namespace EBook.Downloader.Calibre.Opf
{
    /// <remarks/>
    [System.Serializable]
    [System.Xml.Serialization.XmlType(Namespace = Namespaces.Opf, IncludeInSchema = false)]
    public enum ItemsChoiceType
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(contributor))]
        contributor,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(creator))]
        creator,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(date))]
        date,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(description))]
        description,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(identifier))]
        identifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(language))]
        language,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(publisher))]
        publisher,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(subject))]
        subject,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnum(Namespaces.Purl + ":" + nameof(title))]
        title,

        /// <remarks/>
        meta,
    }


}
