// <autogenerated />

namespace EBook.Downloader.Calibre.Opf
{
    /// <remarks/>
    [System.Serializable]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = Namespaces.Opf)]
    public partial class MetadataMeta
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("name")]
        public string Name { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("content")]
        public string Content { get; set; }
    }


}
