// <autogenerated />

namespace EBook.Downloader.Calibre.Opf
{
    /// <remarks/>
    [System.Serializable]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = Namespaces.Opf)]
    [System.Xml.Serialization.XmlRoot(ElementName = "package", Namespace = Namespaces.Opf, IsNullable = false)]
    public class Package
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElement(ElementName = "metadata")]
        public Metadata Metadata { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlArray("manifest")]
        [System.Xml.Serialization.XmlArrayItem("item", IsNullable = false)]
        public Item[] Manifest { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(ElementName = "spine")]
        public Spine Spine { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(ElementName = "guide")]
        public Guide Guide { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("unique-identifier")]
        public string Uniqueidentifier { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("version")]
        public string Version { get; set; }
    }
}
