// <autogenerated />

namespace EBook.Downloader.Calibre.Opf
{
    /// <remarks/>
    [System.Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = "http://www.idpf.org/2007/opf")]
    public partial class SpineItemReference
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute]
        public string idref { get; set; }
    }
}
