// <autogenerated />

namespace EBook.Downloader.Calibre.Opf
{
    /// <remarks/>
    [System.Serializable]
    [System.Diagnostics.DebuggerStepThrough]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(AnonymousType = true, Namespace = "http://www.idpf.org/2007/opf")]
    public partial class Spine
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElement("itemref")]
        public SpineItemReference[] ItemReferences { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttribute("toc")]
        public string TableOfContents { get; set; }
    }
}
